### PR TITLE
Changes to header

### PR DESCRIPTION
**Pull request by scootergrisen**
See: vim/vim#3040

### CODE REVIEW

**Comment by k-takata** [comment]
Please show a reference why `<...>` is preferred than `(...)`.
I don't understand why you want to change `Language-Team:` to `Japanese` from `vim-jp`. Our team name is "vim-jp", not "Japanese".
Should `Language:` be two letter code? Can you show a reference?
Is "UTF-8" better than "utf-8"? I think "utf-8" is widely used and it works fine.

**Comment by scootergrisen** [comment]
Language-Team

    Fill in the English name of the language, and the email address or homepage URL of the language team you are part of.

**Comment by scootergrisen** [comment]
Here is a pot file with "Language-Team: LANGUAGE <LL@li.org>\n":
http://translationproject.org/POT-files/a2ps-4.14.pot

You can also compare with the other po files. The ja*.po files seems to be the only one using (...).

https://www.gnu.org/software/gettext/manual/gettext.html#Header-Entry says:

    Language-Team

    Fill in the English name of the language, and the email address or homepage URL of the language team you are part of.

https://www.gnu.org/software/gettext/manual/gettext.html#Header-Entry says "UTF-8".

**Comment by k-takata** [comment]
It might be better to add a link to the original PR. I edited your comment.

> You can also compare with the other Vim po files. The ja*.po files seems to be the only one using (...).

Only ja*.po are translated by a team and using a URL here. The others uses email addresses.
There's no obvious example using a URL, so I don't know if `<URL>` is preferred.
... But the `<URL>` notation is also used in Markdown and is popular, so this might be acceptable.

> https://www.gnu.org/software/gettext/manual/gettext.html#Header-Entry says "UTF-8".

It also says that:

> The character encoding name can be written in either upper or lower case. Usually upper case is preferred.

It is case insensitive, but "UTF-8" seems to be preferred.

Okay, your PR seems reasonable.
@koron Any thoughts?

**Pull request merged**
